### ISSUE TITLE
rotating camera reset bug

### ISSUE THREAD

**Issue by Mintaras1** [ArtsicleOfficial/camera-smoothing#2]
if you spin camera 360 degrees, sometimes it will "unspin" the camera

https://youtu.be/VSu0-oOZXBs

**Comment by ArtsicleOfficial** [comment]
I'm surprised you managed to do it so consistently. Do you know how I might also reproduce it consistently, or any plugins that could be helping this bug?
I thought I solved the majority of this issue with the [getSmallestAngle](https://github.com/ArtsicleOfficial/camera-smoothing/blob/a1f318d0836f1955254c26a791641dc5c769aacf/src/main/java/com/camerasmoothing/CameraSmoothingPlugin.java#L45) function, but this is surprising.

**Comment by Mintaras1** [comment]
Sorry for slow response, irl stuff...


> how I might also reproduce it consistently

I tried to find most consistent way to provoke "unspin" bug, and found, that if you launch RuneLite, and spin camera to the right, it always does this bug. But if you spin at least once in the opposite direction, it will not do this bug for another spin or two.
Fresh re-launch of RuneLite client: https://youtu.be/rm_hIU2lJHg

> any plugins that could be helping this bug?

I don't think that it's because if some plugin incompatibility. I tried with every plugin disabled, leaving only Camera Smoothing plugin, and managed to still provoke this bug.
All plugins disabled: https://youtu.be/rqE5_cX-VLk


In my testing, i could only provoke this bug by spinning to the right. By spinning to the left, i did not succeed in reproducing this bug.

**Comment by ArtsicleOfficial** [comment]
Huh, thank you for the videos. I've found that I couldn't reproduce this bug myself, however I _will_ try to recreate the algorithm for camera smoothing in a different program and see if it's any of my functions that are operating poorly. I feel that this may likely be the fix as you could only do it in one _direction_, however it is strange that I couldn't reproduce it.

I'm personally using Windows 10 and in the video I switch the GPU on/off. I didn't get this issue with the Camera plugin on, so I turned it off for the video to see if that may cause it. It didn't.
Here is my attempt to recreate the bug (after just having logged in): https://youtu.be/9eStpMiWWVg

**Comment by Mintaras1** [comment]
In those videos, i was using Windows11, so i had a suspicion that it might be something wrong with that. Now, I'm converting my daily driver computer into Linux as main OS, and tried to reproduce same bug.. with success..

https://youtu.be/Q5Mo6Mjh-ZA

**Comment by ArtsicleOfficial** [comment]
I've done a bit of an investigation on the error, and a [fix is currently waiting to be accepted into the plugin hub.](https://github.com/runelite/plugin-hub/pull/2118). Let me know if this fixes it for you.

**Comment by ArtsicleOfficial** [comment]
It's merged; let me know if you still get the bug.

**Comment by Mintaras1** [comment]
Problem solved. Thank you!
