### ISSUE TITLE
Not zooming

### ISSUE THREAD

**Issue by pidbullz** [ArtsicleOfficial/camera-smoothing#3]
I installed the plugin, yet all it does is tilt my screen up and down, it will not allow zooming anymore and doesnt do the smoothness. Not sure what other plugin might be interfering thus its not working for me

**Comment by ArtsicleOfficial** [comment]
What's your smoothing setting at in Camera Smoothing's settings? At 100%, I'd imagine you only get tilting up and down. Do you have "Smooth Zooming" and "Smooth Rotation" checked?
What camera plugins do you have installed? The main ones I'm aware of that I _don't_ use are:
- Camera Fun
- Two step zoom
- Zoom Extender

Please post your RuneLite default Camera plugin settings if you are using it. These are mine, for example:
![image](https://user-images.githubusercontent.com/35227462/176684400-348ce8f7-0682-4d01-96fd-0a978b97871d.png)

**Comment by pidbullz** [comment]
Heya, bit late getting back to you, but here we go:
It never worked for me, u described it well, all others I've used last week
are
Camera Points
Two step zoom

Never used camera fun or zoom extender

Camera plugin settings:
[image: image.png]

Op do 30 jun. 2022 om 15:08 schreef ArtsicleOfficial <
***@***.***>:

**Comment by ArtsicleOfficial** [comment]
> Heya, bit late getting back to you, but here we go: It never worked for me, u described it well, all others I've used last week are Camera Points Two step zoom Never used camera fun or zoom extender Camera plugin settings: [image: image.png] Op do 30 jun. 2022 om 15:08 schreef ArtsicleOfficial < ***@***.***>:

Your image of the camera plugin settings is not displaying.

What is your in-game smoothing setting? Tell me what it is, and make sure it's not 100%.

Try disabling other camera plugins and see if it fixes it.

**Comment by pidbullz** [comment]
Aha, it wasn't working due to 100%, it seems to work now.. :) if that was mentioned somewhere I must have not seen it. Thank you!
