### ISSUE TITLE
unable to rotate camera

### ISSUE THREAD

**Issue by compresm** [ArtsicleOfficial/camera-smoothing#5]
camera wont rotate with plugin active as of 1/12/23. keeps camera faced North

**Comment by compresm** [comment]
just noticed only happens at 100% smoothness. also zoom smoothness enabled in bugged and zooms in and out in flashes

**Comment by ArtsicleOfficial** [comment]
I could have prevented users from using 100% smoothness but I figured some people might find fun challenges to do with it, so I left it in. Make a new issue comprehensively and elegantly reproducing a bug if you find one, otherwise I assume this is all done with.
