### ISSUE TITLE
Camera doesn't zoom when Smooth Zoom is set to 100%

### ISSUE THREAD

**Issue by Speeddymon** [ArtsicleOfficial/camera-smoothing#6]
With Smooth Zoom enabled, I'm unable to zoom in and out on the camera at all but can adjust the pitch and angle, and zoom the minimap without issue. If I uncheck smooth zoom, then the camera zoom functions fine.

Is this a bug or a conflict with something? I use the other plugin "Camera" and enable inner zoom limit expansion, raise outer zoom limit expansion to 400, and expand the pitch limit. The rest of the settings for that plugin are the defaults. For the "Camera Smoothing" plugin, I set smoothness to 100% and enabled both smooth rotation and smooth zoom.

**Comment by ArtsicleOfficial** [comment]
Don't set smoothness to 100%. 100% smoothness making you unable to do certain things is just how the math works, and I left it in in-case any content creators or friends want to do challenges with that setting at 100%. It should work without 100% smoothness, I think? Basically "100% smoothness" is "100% delayed movement" a.k.a. "never move." (Each frame it does 0% of the desired movement)
https://github.com/ArtsicleOfficial/camera-smoothing/blob/2a5ab5fed27b3fe89a1c339b98fb6d6df772a6fe/src/main/java/com/camerasmoothing/CameraSmoothingPlugin.java#L81

You should be able to toggle the Camera plugin to see if that is a conflict (last I checked it doesn't conflict).

But I haven't logged into RS in a while, so I don't know if anything else changed.

**Comment by Speeddymon** [comment]
It works. I lowered it to 90%. Thank you.
